name: MSBuild

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*.*'  # Release tags like v1.2.3.4

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Locate .sln file and set SOLUTION_NAME
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          if (-not $sln) {
            Write-Error "No .sln file found"
            exit 1
          }
          $solutionName = [System.IO.Path]::GetFileNameWithoutExtension($sln.Name)
          echo "SOLUTION_NAME=$solutionName" >> $env:GITHUB_ENV
          echo "SOLUTION_PATH=$($sln.FullName)" >> $env:GITHUB_ENV

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install v143 toolset (VS 2022)
        run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.v143" -y

      - name: Build project
        run: msbuild "${{ env.SOLUTION_PATH }}" /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SOLUTION_NAME }}-artifacts
          path: Release/**
          if-no-files-found: error

      - name: Zip Build Artifacts
        run: |
          $zipName = "${{ env.SOLUTION_NAME }}.zip"
          if (Test-Path "Release/${{ env.SOLUTION_NAME }}") {
            Compress-Archive -Path "Release/${{ env.SOLUTION_NAME }}/*" -DestinationPath $zipName
          } elseif (Test-Path "Release") {
            Compress-Archive -Path "Release/*" -DestinationPath $zipName
          } else {
            Write-Error "Release folder not found"
            exit 1
          }
        shell: pwsh

      - name: Generate Changelog
        run: |
          git log --pretty=format:"- %h %s" -n 20 > CHANGELOG.txt
        shell: pwsh

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.SOLUTION_NAME }}.zip
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
